/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leclaironraporteur;

import java.io.Console;
import java.util.*;
import javax.swing.*;
import javax.swing.plaf.basic.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.bulenkov.darcula.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;

/**
 *
 * @author mrpar_000
 */
public class LoginWindow extends javax.swing.JFrame {

    
    private static Properties hashtable = new Properties();
    private boolean _presse;
    private MainWindow mainWindow;
    
    public MainWindow getMainWindow(){return mainWindow;}
    public void setMainWindow(MainWindow mw){mainWindow = mw;}
    
    public boolean isPresse(){return _presse;}
    public void setPresse(boolean p){_presse=p;}
    
    public Properties getHashtable(){return hashtable;}
    private void setHashtable(Properties h){hashtable=h;}
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        setPresse(false);
        try {
            FileInputStream in = new FileInputStream("config.properties");
            getHashtable().load(in);
        } catch (FileNotFoundException ex) {
            getHashtable().put("admin", "adMin");
        }
        catch(IOException e)
        {
            new JDialog(this, "IOexceptionLogin").setVisible(true);
        }
        
        login.setText("adMin");
        motDePasse.setText("admin");
    }
    
    public LoginWindow(Properties h) {
        initComponents();
        setHashtable(h);
    }
    
    public LoginWindow(MainWindow m)
    {
        setMainWindow(m);
        setPresse(true);
        initComponents();
        try {
            FileInputStream in = new FileInputStream("config.properties");
            getHashtable().load(in);
        } catch (FileNotFoundException ex) {
            getHashtable().put("admin", "adMin");
        }
        catch(IOException e)
        {
            new JDialog(this, "IOexceptionLogin").setVisible(true);
        }
        login.setText("adMin");
        motDePasse.setText("admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        motDePasse = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENUE !");

        jLabel2.setText("Nom d'utilisateur :");

        jLabel3.setText("Mot de passe :");

        valider.setMnemonic('f');
        valider.setText("Valider");
        valider.setToolTipText("");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        motDePasse.setToolTipText("");
        motDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motDePasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(motDePasse))))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(valider)
                .addGap(53, 53, 53)
                .addComponent(annuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(motDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        try{
            String[] tmp = verificationLogin(String.valueOf(motDePasse.getPassword()), login.getText());
            if(isPresse())
            {
                PresseWindow fenPrinc = new PresseWindow();
                fenPrinc.addNotifyNewsListener(getMainWindow());
                fenPrinc.setVisible(true);
                
                getMainWindow().setPResseWindow(fenPrinc);
                getMainWindow().addNotifyNewsListener(fenPrinc);
                
                this.dispose();
            }
            else
            {
                MainWindow fenPrinc = new MainWindow(tmp[0], tmp[1], getHashtable());
                fenPrinc.setVisible(true);
                this.dispose();
            }
        }
        catch(LoginException e)
        {
            e.display();
            motDePasse.setText("");
        }
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        dispose();
    }//GEN-LAST:event_annulerActionPerformed

    private void motDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motDePasseActionPerformed

    public String[] verificationLogin(String key, String loglog) throws LoginException
    {
        String log = (String)getHashtable().get(key);
        System.out.println(log);
        if(log!=null)
        {
            if(log.equals(loglog))
            {
                String prenom = new String();
                String nom = new String();
                for(int i=1; i<log.length();i++)
                {
                    if(Character.isUpperCase(log.charAt(i)))
                    {
                        prenom=log.substring(0, i);
                        nom=log.substring(i, log.length());
                        break;
                    }
                }
                String[] tmp = new String[2];
                tmp[0] = prenom;
                tmp[1] = nom;
                return tmp;
            }
            else
            {
                throw new LoginException(LoginException.LogException.INVALIDLOG);
            }
        }
        else
        {
            throw new LoginException(LoginException.LogException.INVALIDPWD);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            BasicLookAndFeel darcula = new DarculaLaf();
            UIManager.setLookAndFeel(darcula);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField motDePasse;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
