package leclaironraporteur;

import claironBeans.NotifyNewsEvent;
import claironBeans.NotifyNewsListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultButtonModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import network.NetworkBasicClient;
import network.NetworkBasicServer;

/**
 *
 * @author alexa
 */
public final class PresseWindow extends javax.swing.JFrame implements NotifyNewsListener{

    private ArrayList<News> listeNews;
    private NetworkBasicClient basicClient;
    private NetworkBasicServer basicServer;
    private ArrayList<NotifyNewsListener> mailinglist;
    private int taille;
    
    public NetworkBasicClient getNetworkBasicClient(){return basicClient;}
    public void setNetworkBasicClient(NetworkBasicClient nbc){basicClient=nbc;}
    
    public NetworkBasicServer getBasicServer() {return basicServer;}
    public void setBasicServer(NetworkBasicServer nbs){basicServer=nbs;}
    
    public ArrayList<News> getListeNews(){return listeNews;}
    public void setListeNews(ArrayList<News> l){listeNews = l;}
    
    public ArrayList<NotifyNewsListener> getMailingList(){return mailinglist;}
    public void setMailingList(ArrayList<NotifyNewsListener> a){mailinglist = a;}
    
    public int getTaille(){return taille;}
    public void setTaille(int t) {taille = t;}
            
    public PresseWindow() {
        initComponents();
        setListeNews(new ArrayList<News>());
        
        ArrayList<NotifyNewsListener> blou = new ArrayList<NotifyNewsListener>();
        setMailingList(blou);
        
        NetworkBasicClient nbc = new NetworkBasicClient("localhost", 50002);
        setNetworkBasicClient(nbc);
        
        NetworkBasicServer nbs = new NetworkBasicServer(50003, checkBoxRepRecue);
        setBasicServer(nbs);
        

        checkBoxRepRecue.setVisible(false);
        
        String header[] = {"News", "Type", "Important", "Journaliste"};
  
        for(int i=0;i<Table_News.getColumnCount();i++)
        {
            TableColumn tabCol = Table_News.getTableHeader().getColumnModel().getColumn(i);

            tabCol.setHeaderValue(header[i]);
        } 
    }

    @Override
    public void NotifyNewsDetected(NotifyNewsEvent e)
    {
        try {
            TimeUnit.MILLISECONDS.sleep(10); // Exécution trop rapide sans un délais, on lit "RIEN"
        } catch (InterruptedException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        String message = getBasicServer().getMessage();
        if(message.equals("RIEN"))
        {
            return;
        }
        else
        {
            label_rep.setText(message);
            addLog("Confirmation reçue ! ");
        }
        
    }
    
    public void updateTable()
    {
        for(int i=0;i<getTaille();i++) // On vide la JTable
        {
            for(int j=0;j<4;j++)
            {
                Table_News.setValueAt("", i, j);
            }
        }
        
        for(int i=0;i<getListeNews().size();i++) // On remplit la JTable avec notre ArrayList de news
        {
            News tmp = getListeNews().get(i);
            
            Table_News.getModel().setValueAt(tmp.getTitre(), i, 0);
            Table_News.getModel().setValueAt(tmp.getCategorie().getLibelle(), i, 1);
            
            if(tmp.isImportant())
                Table_News.getModel().setValueAt("Y", i, 2);
            else
                Table_News.getModel().setValueAt("F", i, 2);
            
            Table_News.getModel().setValueAt(tmp.getnomJournaliste(), i, 3);
        }        
    }
    
    public void addLog(String s)
    {
        Date date = new Date();
        Calendar calendar = GregorianCalendar.getInstance();
        calendar.setTime(date);
        
        String log = "["+calendar.get(Calendar.HOUR_OF_DAY)+":"+calendar.get(Calendar.MINUTE)+"] "+s; // Heure:Minute + Message
        
        textAreaLog.append(log+System.getProperty("line.separator")); // Ira à la ligne peu importe l'OS
    }
    
    public void addNotifyNewsListener(NotifyNewsListener nnl)
    {
        getMailingList().add(nnl);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        checkBoxRepRecue = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_Journaliste = new javax.swing.JTextField();
        TF_Titre = new javax.swing.JTextField();
        TF_Texte = new javax.swing.JTextField();
        RB_Pol = new javax.swing.JRadioButton();
        RB_Inter = new javax.swing.JRadioButton();
        RB_Sports = new javax.swing.JRadioButton();
        RB_Ragots = new javax.swing.JRadioButton();
        CB_Important = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TA_Logs = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_News = new javax.swing.JTable();
        buttonAnnuler = new javax.swing.JButton();
        buttonEnvoyer = new javax.swing.JButton();
        buttonEnreistrer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label_rep = new javax.swing.JLabel();
        label_nbnews = new javax.swing.JLabel();
        buttonSupprimer = new javax.swing.JButton();

        checkBoxRepRecue.setText("Reponse recues !");
        checkBoxRepRecue.setEnabled(false);
        checkBoxRepRecue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxRepRecueActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Point Presse");

        jLabel1.setText("Journaliste :");

        jLabel2.setText("Titre :");

        jLabel3.setText("Texte :");

        TF_Journaliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JournalisteActionPerformed(evt);
            }
        });

        TF_Titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TitreActionPerformed(evt);
            }
        });

        TF_Texte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TexteActionPerformed(evt);
            }
        });

        buttonGroup.add(RB_Pol);
        RB_Pol.setText("Politique");
        RB_Pol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_PolActionPerformed(evt);
            }
        });

        buttonGroup.add(RB_Inter);
        RB_Inter.setText("International");

        buttonGroup.add(RB_Sports);
        RB_Sports.setText("Sports");

        buttonGroup.add(RB_Ragots);
        RB_Ragots.setText("Ragots");

        CB_Important.setText("Important");

        jLabel4.setText("Nombre de news envoyés pendant cette session :");

        jLabel5.setText("Log des news :");

        textAreaLog.setColumns(20);
        textAreaLog.setRows(5);
        TA_Logs.setViewportView(textAreaLog);

        Table_News.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_News);

        buttonAnnuler.setText("Annuler");
        buttonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnnulerActionPerformed(evt);
            }
        });

        buttonEnvoyer.setText("Envoyer");
        buttonEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnvoyerActionPerformed(evt);
            }
        });

        buttonEnreistrer.setText("Enregistrer");
        buttonEnreistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnreistrerActionPerformed(evt);
            }
        });

        jLabel6.setText("Réponse :");

        label_rep.setText("---");

        label_nbnews.setText("0");

        buttonSupprimer.setText("Supprimer");
        buttonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(buttonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TF_Journaliste, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                            .addComponent(TF_Titre)
                                            .addComponent(TF_Texte)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(RB_Inter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addComponent(RB_Pol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RB_Ragots, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(RB_Sports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CB_Important, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonEnreistrer)
                                    .addComponent(label_rep, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TA_Logs, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_nbnews, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TF_Journaliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TF_Texte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(RB_Pol)
                        .addGap(18, 18, 18)
                        .addComponent(RB_Inter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Sports)
                            .addComponent(buttonEnreistrer))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RB_Ragots)
                                .addGap(18, 18, 18)
                                .addComponent(CB_Important))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(label_nbnews))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSupprimer)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(TA_Logs, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_rep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAnnuler)
                    .addComponent(buttonEnvoyer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_JournalisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JournalisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JournalisteActionPerformed

    private void TF_TitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TitreActionPerformed

    private void TF_TexteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TexteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TexteActionPerformed

    private void RB_PolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_PolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_PolActionPerformed

    private void buttonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnnulerActionPerformed
        dispose();
    }//GEN-LAST:event_buttonAnnulerActionPerformed

    private void buttonEnreistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnreistrerActionPerformed
        

        if(buttonGroup.getSelection() != null && !TF_Titre.getText().equals("") && !TF_Journaliste.getText().equals(""))
        {
            News news = new News();
            news.setTitre(TF_Titre.getText());
            news.setText(TF_Texte.getText());
            news.setnomJournaliste(TF_Journaliste.getText());

            // On définit la catégorie selon le radiobutton sélectionné
            if(RB_Inter.isSelected())news.setCategorie(Categorie.INTERNATIONAL);
            else if(RB_Pol.isSelected())news.setCategorie(Categorie.POLITIQUE);
            else if(RB_Sports.isSelected())news.setCategorie(Categorie.SPORT);
            else if(RB_Ragots.isSelected())news.setCategorie(Categorie.RAGOT);


            news.setImportant(CB_Important.isSelected());

            getListeNews().add(news);

            TF_Titre.setText("");
            TF_Texte.setText("");
            TF_Journaliste.setText("");
            buttonGroup.clearSelection();
            CB_Important.setSelected(false);

            addLog("News enregistree avec succes ! ("+news.getnomJournaliste()+")");

            updateTable();      
        }
        
        
    }//GEN-LAST:event_buttonEnreistrerActionPerformed

    private void buttonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerActionPerformed
        setTaille(getListeNews().size());
        getListeNews().remove(Table_News.getSelectedRow());
        
        addLog("News supprimée ");
        updateTable();
    }//GEN-LAST:event_buttonSupprimerActionPerformed

    private void buttonEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnvoyerActionPerformed
      
        int nb = Integer.parseInt(label_nbnews.getText());
        nb = nb + listeNews.size();
        label_nbnews.setText(Integer.toString(nb));
        
        for(int i = 0; i < listeNews.size(); i++)
        {
            News tmp = getListeNews().get(i);
            
            basicClient.sendStringWithoutWaiting(tmp.toString());
            
            NotifyNewsEvent nne = new NotifyNewsEvent();
            
            for(int j=0;j<getMailingList().size();j++)
            {
                getMailingList().get(j).NotifyNewsDetected(nne);
            }
        }
        
        setTaille(getListeNews().size());
        
        getListeNews().removeAll(listeNews);
        
        updateTable();
        
        addLog(getTaille() + " News envoyées ");
        
    }//GEN-LAST:event_buttonEnvoyerActionPerformed

    private void checkBoxRepRecueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxRepRecueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxRepRecueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB_Important;
    private javax.swing.JRadioButton RB_Inter;
    private javax.swing.JRadioButton RB_Pol;
    private javax.swing.JRadioButton RB_Ragots;
    private javax.swing.JRadioButton RB_Sports;
    private javax.swing.JScrollPane TA_Logs;
    private javax.swing.JTextField TF_Journaliste;
    private javax.swing.JTextField TF_Texte;
    private javax.swing.JTextField TF_Titre;
    private javax.swing.JTable Table_News;
    private javax.swing.JButton buttonAnnuler;
    private javax.swing.JButton buttonEnreistrer;
    private javax.swing.JButton buttonEnvoyer;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonSupprimer;
    private javax.swing.JCheckBox checkBoxRepRecue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nbnews;
    private javax.swing.JLabel label_rep;
    private javax.swing.JTextArea textAreaLog;
    // End of variables declaration//GEN-END:variables
}
