/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leclaironraporteur;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author alexa
 */
public class RechercheCatégorieWindow extends javax.swing.JFrame {

    /**
     * Creates new form RechercheCatégorieWindow
     */
    MainWindow mw;
    
    private javax.swing.DefaultComboBoxModel comboBoxCatModel;
    
    public DefaultComboBoxModel getComboBoxCatModel() {return comboBoxCatModel;}
    public void setComboBoxCatModel(DefaultComboBoxModel dcbm) {comboBoxCatModel=dcbm;}
    
    private DefaultListModel modelres = new DefaultListModel();
    
    public DefaultListModel getListResModel() {return modelres;}    
    public void setListResModel(DefaultListModel dlm) {modelres = dlm;}
    
    public RechercheCatégorieWindow() {
        initComponents();
        list_resultat.setModel(modelres);
    }
    public RechercheCatégorieWindow(MainWindow aThis) {
        initComponents();
        mw = aThis;
        list_resultat.setModel(modelres);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBox_cat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_resultat = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recherche d'une news par catégorie");

        jLabel1.setText("Catégorie :");

        ComboBox_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "International", "Politique", "Sport", "Ragot" }));

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        list_resultat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_resultatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_resultat);

        jButton2.setText("Terminer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Recherche par Catégorie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton2)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultListModel dlm = new DefaultListModel();
        int i;
        
        String tmp = (String)ComboBox_cat.getSelectedItem();
        
        if(tmp!=null)
        {
            switch(tmp) // Selon le résultat on remplit notre liste élément par élément
            {
                case "Politique" :  dlm = mw.getListPolModel();
                                    for(i = 0; i < dlm.getSize(); i++)
                                    {
                                        modelres.addElement(dlm.getElementAt(i));
                                    }
                                    setListResModel(modelres);
                                    break;
                                    
                case "International" :  dlm = mw.getListInterModel();
                                        for(i = 0; i < dlm.getSize(); i++)
                                        {
                                            modelres.addElement(dlm.getElementAt(i));
                                        }
                                        setListResModel(modelres);
                                        break;
                                        
                case "Sport" :  dlm = mw.getListSportModel();
                                for(i = 0; i < dlm.getSize(); i++)
                                {
                                    modelres.addElement(dlm.getElementAt(i));
                                }
                                setListResModel(modelres);
                                break;
                                
                case "Ragot" :  dlm = mw.getListRagotModel();
                                for(i = 0; i < dlm.getSize(); i++)
                                {
                                    modelres.addElement(dlm.getElementAt(i));
                                }
                                setListResModel(modelres);
                                break;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void list_resultatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_resultatMouseClicked
        if (evt.getClickCount() == 2)
        {
            String mot;
            mot = list_resultat.getSelectedValue();
            News news = new News();
            ArrayList<News> listeNews = new ArrayList<News>();
            listeNews = mw.getListeNews();
            
            int i = 0;
            while(!mot.equals(listeNews.get(i).getTitre())) // On cherche la news dans le vecteur
            {
                i++;
            }
            
            news = listeNews.get(i);
            
            MotResultatWindow mrw = new MotResultatWindow(news);
            mrw.setVisible(true);
        }
    }//GEN-LAST:event_list_resultatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheCatégorieWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheCatégorieWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheCatégorieWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheCatégorieWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheCatégorieWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_cat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_resultat;
    // End of variables declaration//GEN-END:variables
}
